// <auto-generated />
using System;
using AMS.Modules.Allocations.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.Allocations.Persistence.Migrations
{
    [DbContext(typeof(AllocationsDbContext))]
    [Migration("20260812091340_20260812_Allocations_Revision3")]
    partial class _20260812_Allocations_Revision3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Allocations")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AllocationReturnReversal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<int?>("HandoverId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousAssetStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PreviousReturnedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RestoredEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ReversedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReversedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_AllocationReturnReversal");

                    b.HasIndex("AllocationId")
                        .HasDatabaseName("IX_AllocationReturnReversal_AllocationId");

                    b.ToTable("AllocationReturnReversal", "Allocations");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetAcknowledgement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("ManagerApprovedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagerUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SignatureImagePath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("SignedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_AssetAcknowledgement");

                    b.HasIndex("AllocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetAcknowledgement_Allocation");

                    b.ToTable("AssetAcknowledgement", "Allocations");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AllocatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpectedReturnDate")
                        .HasColumnType("date");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnRequestedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_AssetAllocation");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetAllocation_OneActivePerAsset")
                        .HasFilter("[ReturnedOnUtc] IS NULL");

                    b.HasIndex("ExpectedReturnDate")
                        .HasDatabaseName("IX_AssetAllocation_Overdue")
                        .HasFilter("[ReturnedOnUtc] IS NULL");

                    b.HasIndex("LocationId", "EmployeeId")
                        .HasDatabaseName("IX_AssetAllocation_LocationEmployee");

                    b.ToTable("AssetAllocation", "Allocations");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetAllocationApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllocationId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_AssetAllocationApproval");

                    b.HasIndex("Status", "LocationId")
                        .HasDatabaseName("IX_AssetAllocationApproval_Queue");

                    b.ToTable("AssetAllocationApproval", "Allocations");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetHandover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("BranchLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispatchedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HandedOverOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReceivedByHo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MovementId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReceivedAtHoByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAtHoOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReturnCondition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_AssetHandover");

                    b.HasIndex("AllocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetHandover_OnePerAllocation")
                        .HasFilter("[CancelledOnUtc] IS NULL");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetHandover_OneOpenPerAsset")
                        .HasFilter("[Status] = N'HandedOver'");

                    b.HasIndex("BranchLocationId", "Status")
                        .HasDatabaseName("IX_AssetHandover_BranchQueue");

                    b.HasIndex("Status", "DispatchedOnUtc")
                        .HasDatabaseName("IX_AssetHandover_GrnQueue")
                        .HasFilter("[IsReceivedByHo] = 0");

                    b.ToTable("AssetHandover", "Allocations", t =>
                        {
                            t.HasCheckConstraint("CK_AssetHandover_CancelPair", "(([Status] = N'Cancelled' AND [CancelledOnUtc] IS NOT NULL) OR ([Status] <> N'Cancelled' AND [CancelledOnUtc] IS NULL))");

                            t.HasCheckConstraint("CK_AssetHandover_Condition", "([ReturnCondition] IN (N'Good', N'MinorDamage', N'Damaged', N'NotWorking', N'Missing'))");

                            t.HasCheckConstraint("CK_AssetHandover_ReceiptPair", "(([IsReceivedByHo] = 0 AND [ReceivedAtHoOnUtc] IS NULL) OR ([IsReceivedByHo] = 1 AND [ReceivedAtHoOnUtc] IS NOT NULL))");

                            t.HasCheckConstraint("CK_AssetHandover_ReceiptStatus", "(([Status] = N'ReceivedAtHo' AND [IsReceivedByHo] = 1) OR ([Status] <> N'ReceivedAtHo' AND [IsReceivedByHo] = 0))");

                            t.HasCheckConstraint("CK_AssetHandover_Status", "([Status] IN (N'HandedOver', N'InTransitToHo', N'ReceivedAtHo', N'Cancelled'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetReturnImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CapturedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("HandoverId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_AssetReturnImage");

                    b.HasIndex("AllocationId")
                        .HasDatabaseName("IX_AssetReturnImage_AllocationId");

                    b.HasIndex("HandoverId")
                        .HasDatabaseName("IX_AssetReturnImage_HandoverId");

                    b.ToTable("AssetReturnImage", "Allocations");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetSiteMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CommissionedDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerSiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MappedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RemovedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_AssetSiteMapping");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetSiteMapping_OneActivePerAsset")
                        .HasFilter("[RemovedOnUtc] IS NULL");

                    b.HasIndex("CustomerSiteId")
                        .HasDatabaseName("IX_AssetSiteMapping_CustomerSiteId");

                    b.ToTable("AssetSiteMapping", "Allocations");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.CustomerSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_CustomerSite");

                    b.ToTable("CustomerSite", "Allocations");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AllocationReturnReversal", b =>
                {
                    b.HasOne("AMS.Modules.Allocations.Domain.AssetAllocation", null)
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AllocationReturnReversal_AssetAllocation_AllocationId");

                    b.HasOne("AMS.Modules.Allocations.Domain.AssetHandover", null)
                        .WithMany()
                        .HasForeignKey("HandoverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AllocationReturnReversal_AssetHandover_HandoverId");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetAcknowledgement", b =>
                {
                    b.HasOne("AMS.Modules.Allocations.Domain.AssetAllocation", null)
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetAcknowledgement_AssetAllocation_AllocationId");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetHandover", b =>
                {
                    b.HasOne("AMS.Modules.Allocations.Domain.AssetAllocation", null)
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetHandover_AssetAllocation_AllocationId");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetReturnImage", b =>
                {
                    b.HasOne("AMS.Modules.Allocations.Domain.AssetAllocation", null)
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetReturnImage_AssetAllocation_AllocationId");

                    b.HasOne("AMS.Modules.Allocations.Domain.AssetHandover", null)
                        .WithMany()
                        .HasForeignKey("HandoverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetReturnImage_AssetHandover_HandoverId");
                });

            modelBuilder.Entity("AMS.Modules.Allocations.Domain.AssetSiteMapping", b =>
                {
                    b.HasOne("AMS.Modules.Allocations.Domain.CustomerSite", null)
                        .WithMany()
                        .HasForeignKey("CustomerSiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetSiteMapping_CustomerSite_CustomerSiteId");
                });
#pragma warning restore 612, 618
        }
    }
}
