// <auto-generated />
using System;
using AMS.Modules.Assets.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.Assets.Persistence.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    [Migration("20260812063333_20260812_Assets_Initial")]
    partial class _20260812_Assets_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Assets")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.Assets.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date");

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("AssetStatusId")
                        .HasColumnType("int");

                    b.Property<string>("BarcodeValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("CalibrationEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CalibrationStartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ErpAssetNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hostname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPhysicalCheckOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSapSyncOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrCodeValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SapAssetClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SapAssetNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SapPlant")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime");

                    b.HasKey("Id")
                        .HasName("PK_Asset");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("IX_Asset_AssetCategoryId");

                    b.HasIndex("AssetNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Asset_Number");

                    b.HasIndex("AssetStatusId")
                        .HasDatabaseName("IX_Asset_AssetStatusId");

                    b.HasIndex("QrCodeValue")
                        .IsUnique()
                        .HasDatabaseName("UX_Asset_QrCode")
                        .HasFilter("[QrCodeValue] IS NOT NULL");

                    b.HasIndex("SapAssetNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Asset_SapNumber")
                        .HasFilter("[SapAssetNumber] IS NOT NULL");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("IX_Asset_Serial");

                    b.HasIndex("CurrentLocationId", "AssetStatusId")
                        .HasDatabaseName("IX_Asset_LocationStatus");

                    b.ToTable("Asset", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_Asset_CalibrationWindow", "([CalibrationEndDate] IS NULL OR [CalibrationStartDate] IS NULL OR [CalibrationEndDate] >= [CalibrationStartDate])");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AssetHistory", "Assets");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_AssetCategory");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetCategory_Name");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("IX_AssetCategory_ParentCategoryId");

                    b.ToTable("AssetCategory", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetCustomValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("CustomFieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id")
                        .HasName("PK_AssetCustomValue");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("IX_AssetCustomValue_OptionId");

                    b.HasIndex("AssetId", "CustomFieldDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetCustomValue_AssetField");

                    b.HasIndex("CustomFieldDefinitionId", "ValueNumber")
                        .HasDatabaseName("IX_AssetCustomValue_NumericLookup");

                    b.ToTable("AssetCustomValue", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AllocationId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNameSnapshot")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("EventOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HandoverId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationNameSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MovementId")
                        .HasColumnType("int");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("VerificationId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_AssetEvent");

                    b.HasIndex("AssetId", "EventOnUtc")
                        .HasDatabaseName("IX_AssetEvent_Asset");

                    b.ToTable("AssetEvent", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetHardwareDetail", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("ChassisType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MemoryGb")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonitorModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MonitorSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Processor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("StorageGb")
                        .HasColumnType("int");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetHardwareDetail");

                    b.ToTable("AssetHardwareDetail", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetPurchaseDetail", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("WarrantyStartDate")
                        .HasColumnType("date");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetPurchaseDetail");

                    b.ToTable("AssetPurchaseDetail", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_AssetPurchaseDetail_WarrantyWindow", "([WarrantyEndDate] IS NULL OR [WarrantyStartDate] IS NULL OR [WarrantyEndDate] >= [WarrantyStartDate])");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetSoftwareDetail", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Antivirus")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Architecture")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfficeVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OperatingSystemBuild")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("OsKeyEncrypted")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetSoftwareDetail");

                    b.ToTable("AssetSoftwareDetail", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_AssetStatus");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetStatus_Name");

                    b.ToTable("AssetStatus", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.CustomFieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationRegex")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id")
                        .HasName("PK_CustomFieldDefinition");

                    b.HasIndex("AssetCategoryId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomFieldDefinition_CategoryField");

                    b.ToTable("CustomFieldDefinition", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_CustomFieldDefinition_Range", "([MinValue] IS NULL OR [MaxValue] IS NULL OR [MaxValue] >= [MinValue])");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.CustomFieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomFieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_CustomFieldOption");

                    b.HasIndex("CustomFieldDefinitionId", "OptionValue")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomFieldOption_Value");

                    b.ToTable("CustomFieldOption", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.Asset", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Asset_AssetCategory_AssetCategoryId");

                    b.HasOne("AMS.Modules.Assets.Domain.AssetStatus", null)
                        .WithMany()
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Asset_AssetStatus_AssetStatusId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetCategory", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetCategory_AssetCategory_ParentCategoryId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetCustomValue", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetCustomValue_Asset_AssetId");

                    b.HasOne("AMS.Modules.Assets.Domain.CustomFieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetCustomValue_CustomFieldDefinition_CustomFieldDefinitionId");

                    b.HasOne("AMS.Modules.Assets.Domain.CustomFieldOption", null)
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetCustomValue_CustomFieldOption_OptionId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetEvent", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetEvent_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetHardwareDetail", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetHardwareDetail_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetPurchaseDetail", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetPurchaseDetail_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetSoftwareDetail", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetSoftwareDetail_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.CustomFieldDefinition", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CustomFieldDefinition_AssetCategory_AssetCategoryId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.CustomFieldOption", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.CustomFieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomFieldOption_CustomFieldDefinition_CustomFieldDefinitionId");
                });
#pragma warning restore 612, 618
        }
    }
}
