// <auto-generated />
using System;
using AMS.Modules.Assets.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.Assets.Persistence.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    partial class AssetsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Assets")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.Assets.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date");

                    b.Property<int?>("AssetClassId")
                        .HasColumnType("int");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("AssetStatusId")
                        .HasColumnType("int");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("BarcodeValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CapitalisedFromAssetId")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()", "DF_Asset_ConcurrencyStamp");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ErpAssetNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<string>("ImportedDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBulk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_Asset_IsBulk");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPhysicalCheckOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSapSyncOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrCodeValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValueSql("1", "DF_Asset_Quantity");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SapAssetClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SapAssetNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SapPlant")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SplitFromAssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Asset");

                    b.HasIndex("AssetClassId")
                        .HasDatabaseName("IX_Asset_AssetClassId");

                    b.HasIndex("AssetNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Asset_Number");

                    b.HasIndex("AssetStatusId")
                        .HasDatabaseName("IX_Asset_AssetStatusId");

                    b.HasIndex("AssetTypeId")
                        .HasDatabaseName("IX_Asset_AssetTypeId");

                    b.HasIndex("CapitalisedFromAssetId")
                        .HasDatabaseName("IX_Asset_CapitalisedFromAssetId");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("IX_Asset_ImportBatchId")
                        .HasFilter("[ImportBatchId] IS NOT NULL");

                    b.HasIndex("QrCodeValue")
                        .IsUnique()
                        .HasDatabaseName("UX_Asset_QrCode")
                        .HasFilter("[QrCodeValue] IS NOT NULL");

                    b.HasIndex("SapAssetNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Asset_SapNumber")
                        .HasFilter("[SapAssetNumber] IS NOT NULL");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("IX_Asset_Serial");

                    b.HasIndex("CurrentLocationId", "AssetStatusId")
                        .HasDatabaseName("IX_Asset_LocationStatus");

                    b.ToTable("Asset", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_Asset_BulkHasUom", "([IsBulk] = 0 OR [UnitOfMeasure] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Asset_BulkNotHeld", "([IsBulk] = 0 OR ([CurrentEmployeeId] IS NULL AND [CurrentLocationId] IS NULL))");

                            t.HasCheckConstraint("CK_Asset_QuantityPositive", "([Quantity] > 0)");

                            t.HasCheckConstraint("CK_Asset_UnitQuantityIsOne", "([IsBulk] = 1 OR [Quantity] = 1)");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AssetHistory", "Assets");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuc")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDepreciable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIntangible")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportingCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_AssetClass");

                    b.HasIndex("ClassCode")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetClass_Code");

                    b.HasIndex("ClassName")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetClass_Name");

                    b.HasIndex("IsAuc")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetClass_OneAuc")
                        .HasFilter("[IsAuc] = 1");

                    b.ToTable("AssetClass", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetCustomValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("CustomFieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id")
                        .HasName("PK_AssetCustomValue");

                    b.HasIndex("OptionId")
                        .HasDatabaseName("IX_AssetCustomValue_OptionId");

                    b.HasIndex("AssetId", "CustomFieldDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetCustomValue_AssetField");

                    b.HasIndex("CustomFieldDefinitionId", "ValueNumber")
                        .HasDatabaseName("IX_AssetCustomValue_NumericLookup");

                    b.ToTable("AssetCustomValue", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetDepreciationEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Additions")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChargedForPeriod")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosingAccumulated")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("FinancialYear")
                        .HasColumnType("smallint");

                    b.Property<decimal>("NetBookValueAtClose")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningAccumulated")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SyncedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_AssetDepreciationEntry");

                    b.HasIndex("AssetId", "FinancialYear")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetDepreciationEntry_AssetYear");

                    b.ToTable("AssetDepreciationEntry", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_AssetDepreciationEntry_Source", "([SourceSystem] IN (N'Sap', N'Import'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetDisposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DisposalDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("DisposalGrossValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DisposalQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("DisposalReason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("SaleProceeds")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("PK_AssetDisposal");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("IX_AssetDisposal_AssetId");

                    b.ToTable("AssetDisposal", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_AssetDisposal_QuantityPositive", "([DisposalQuantity] > 0)");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AllocationId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DisposalId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNameSnapshot")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("EventOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HandoverId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationNameSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MovementId")
                        .HasColumnType("int");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("QuantityDelta")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("VerificationId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_AssetEvent");

                    b.HasIndex("AssetId", "EventOnUtc")
                        .HasDatabaseName("IX_AssetEvent_Asset");

                    b.ToTable("AssetEvent", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetFinance", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AccumulatedDepreciation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AccumulatedDepreciationCoaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AdditionalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApVoucherNo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("AucReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CapitalisedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepreciationChargeCoaId")
                        .HasColumnType("int");

                    b.Property<string>("DepreciationMethod")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("DepreciationPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("DisposalGrossValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("FirstAcquisitionDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("GrossValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GrossValueCoaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSyncedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MigratedBookValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetBookValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OpportunityName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OriginalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("PostingDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SapPostingStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UsefulLifeMonths")
                        .HasColumnType("int");

                    b.Property<string>("VoucherNo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetFinance");

                    b.ToTable("AssetFinance", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_AssetFinance_Method", "([DepreciationMethod] IS NULL OR [DepreciationMethod] IN (N'StraightLine', N'WrittenDownValue', N'None'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetHardwareDetail", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("ChassisType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hostname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MemoryGb")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonitorModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MonitorSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Processor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("StorageGb")
                        .HasColumnType("int");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetHardwareDetail");

                    b.ToTable("AssetHardwareDetail", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetHolding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerSiteId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OnHandQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_AssetHolding");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("IX_AssetHolding_Location")
                        .HasFilter("[OnHandQuantity] > 0");

                    b.HasIndex("AssetId", "CustomerSiteId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetHolding_AssetSite")
                        .HasFilter("[CustomerSiteId] IS NOT NULL");

                    b.HasIndex("AssetId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetHolding_AssetLocation")
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.ToTable("AssetHolding", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_AssetHolding_NonNegative", "([OnHandQuantity] >= 0)");

                            t.HasCheckConstraint("CK_AssetHolding_OnePlaceKind", "(([LocationId] IS NOT NULL AND [CustomerSiteId] IS NULL) OR ([LocationId] IS NULL AND [CustomerSiteId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetInstrumentDetail", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("AccuracyClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CalibrationAgency")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("CalibrationEndDate")
                        .HasColumnType("date");

                    b.Property<int?>("CalibrationFrequencyMonths")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CalibrationStartDate")
                        .HasColumnType("date");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeasurementRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetInstrumentDetail");

                    b.HasIndex("CalibrationEndDate")
                        .HasDatabaseName("IX_AssetInstrumentDetail_CalibrationDue");

                    b.ToTable("AssetInstrumentDetail", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_AssetInstrumentDetail_Window", "([CalibrationEndDate] IS NULL OR [CalibrationStartDate] IS NULL OR [CalibrationEndDate] >= [CalibrationStartDate])");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetPurchaseDetail", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("WarrantyStartDate")
                        .HasColumnType("date");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetPurchaseDetail");

                    b.ToTable("AssetPurchaseDetail", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_AssetPurchaseDetail_WarrantyWindow", "([WarrantyEndDate] IS NULL OR [WarrantyStartDate] IS NULL OR [WarrantyEndDate] >= [WarrantyStartDate])");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetSoftwareDetail", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Antivirus")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Architecture")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfficeVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OperatingSystemBuild")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("OsKeyEncrypted")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetSoftwareDetail");

                    b.ToTable("AssetSoftwareDetail", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_AssetStatus");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetStatus_Name");

                    b.ToTable("AssetStatus", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllocatable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1", "DF_AssetType_IsAllocatable");

                    b.Property<bool>("IsBulkDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_AssetType_IsBulkDefault");

                    b.Property<bool>("IsPhysical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1", "DF_AssetType_IsPhysical");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentAssetTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("TracksCalibration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_AssetType_TracksCalibration");

                    b.Property<bool>("TracksHardware")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_AssetType_TracksHardware");

                    b.Property<bool>("TracksSoftware")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_AssetType_TracksSoftware");

                    b.Property<bool>("TracksVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_AssetType_TracksVehicle");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_AssetType");

                    b.HasIndex("ParentAssetTypeId")
                        .HasDatabaseName("IX_AssetType_ParentAssetTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetType_Name");

                    b.ToTable("AssetType", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetVehicleDetail", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FitnessExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("InsuranceExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OdometerKm")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PucExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AssetId")
                        .HasName("PK_AssetVehicleDetail");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_AssetVehicleDetail_Registration");

                    b.ToTable("AssetVehicleDetail", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.ChartOfAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoaCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ChartOfAccount");

                    b.HasIndex("CoaCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ChartOfAccount_Code");

                    b.ToTable("ChartOfAccount", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.CustomFieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationRegex")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id")
                        .HasName("PK_CustomFieldDefinition");

                    b.HasIndex("AssetTypeId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomFieldDefinition_TypeField");

                    b.ToTable("CustomFieldDefinition", "Assets", t =>
                        {
                            t.HasCheckConstraint("CK_CustomFieldDefinition_Range", "([MinValue] IS NULL OR [MaxValue] IS NULL OR [MaxValue] >= [MinValue])");

                            t.HasCheckConstraint("CK_CustomFieldDefinition_Type", "([FieldType] IN (N'Text', N'Number', N'Percentage', N'Date', N'Boolean', N'Dropdown'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.CustomFieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomFieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_CustomFieldOption");

                    b.HasIndex("CustomFieldDefinitionId", "OptionValue")
                        .IsUnique()
                        .HasDatabaseName("UX_CustomFieldOption_Value");

                    b.ToTable("CustomFieldOption", "Assets");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.Asset", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.AssetClass", null)
                        .WithMany()
                        .HasForeignKey("AssetClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Asset_AssetClass_AssetClassId");

                    b.HasOne("AMS.Modules.Assets.Domain.AssetStatus", null)
                        .WithMany()
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Asset_AssetStatus_AssetStatusId");

                    b.HasOne("AMS.Modules.Assets.Domain.AssetType", null)
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Asset_AssetType_AssetTypeId");

                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("CapitalisedFromAssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Asset_Asset_CapitalisedFromAssetId");

                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("SplitFromAssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Asset_Asset_SplitFromAssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetCustomValue", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetCustomValue_Asset_AssetId");

                    b.HasOne("AMS.Modules.Assets.Domain.CustomFieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetCustomValue_CustomFieldDefinition_CustomFieldDefinitionId");

                    b.HasOne("AMS.Modules.Assets.Domain.CustomFieldOption", null)
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetCustomValue_CustomFieldOption_OptionId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetDepreciationEntry", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetDepreciationEntry_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetDisposal", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetDisposal_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetEvent", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetEvent_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetFinance", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.ChartOfAccount", null)
                        .WithMany()
                        .HasForeignKey("AccumulatedDepreciationCoaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetFinance_ChartOfAccount_AccumulatedDepreciationCoaId");

                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetFinance_Asset_AssetId");

                    b.HasOne("AMS.Modules.Assets.Domain.ChartOfAccount", null)
                        .WithMany()
                        .HasForeignKey("DepreciationChargeCoaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetFinance_ChartOfAccount_DepreciationChargeCoaId");

                    b.HasOne("AMS.Modules.Assets.Domain.ChartOfAccount", null)
                        .WithMany()
                        .HasForeignKey("GrossValueCoaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetFinance_ChartOfAccount_GrossValueCoaId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetHardwareDetail", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetHardwareDetail_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetHolding", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AssetHolding_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetInstrumentDetail", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetInstrumentDetail_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetPurchaseDetail", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetPurchaseDetail_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetSoftwareDetail", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetSoftwareDetail_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetType", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.AssetType", null)
                        .WithMany()
                        .HasForeignKey("ParentAssetTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetType_AssetType_ParentAssetTypeId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.AssetVehicleDetail", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AssetVehicleDetail_Asset_AssetId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.CustomFieldDefinition", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.AssetType", null)
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CustomFieldDefinition_AssetType_AssetTypeId");
                });

            modelBuilder.Entity("AMS.Modules.Assets.Domain.CustomFieldOption", b =>
                {
                    b.HasOne("AMS.Modules.Assets.Domain.CustomFieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomFieldOption_CustomFieldDefinition_CustomFieldDefinitionId");
                });
#pragma warning restore 612, 618
        }
    }
}
