// <auto-generated />
using System;
using AMS.Modules.ServiceDesk.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.ServiceDesk.Persistence.Migrations
{
    [DbContext(typeof(ServiceDeskDbContext))]
    [Migration("20260825112609_20260825_ServiceDesk_CategoryClassification")]
    partial class _20260825_ServiceDesk_CategoryClassification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ServiceDesk")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("RequestNumberSequence", "ServiceDesk");

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ApprovalNotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasDefaultValueSql("0", "DF_ApprovalNotificationLog_AttemptCount");

                    b.Property<long?>("EmailOutboxId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("QueuedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("RequestApprovalInstanceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RequestApprovalParticipantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RequestApprovalStepId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SentOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubjectSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id")
                        .HasName("PK_ApprovalNotificationLog");

                    b.HasIndex("EmailOutboxId")
                        .HasDatabaseName("IX_ApprovalNotificationLog_Outbox")
                        .HasFilter("[EmailOutboxId] IS NOT NULL");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ApprovalNotificationLog_Idempotency");

                    b.HasIndex("RequestApprovalInstanceId", "QueuedOnUtc")
                        .HasDatabaseName("IX_ApprovalNotificationLog_Instance");

                    b.ToTable("ApprovalNotificationLog", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalNotificationLog_Attempts", "([AttemptCount] >= 0)");

                            t.HasCheckConstraint("CK_ApprovalNotificationLog_Status", "([Status] IN (N'Queued', N'Sent', N'Failed', N'Skipped'))");

                            t.HasCheckConstraint("CK_ApprovalNotificationLog_Type", "([NotificationType] IN ( N'ApprovalRequired', N'Reminder', N'Escalation', N'StepApproved', N'RequestApproved', N'RequestRejected', N'RequestCancelled' ))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ApprovalStageApproverRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalWorkflowStageId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1", "DF_ApprovalStageApproverRule_IsRequired");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolverCapabilityName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ResolverEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ResolverRoleId")
                        .HasColumnType("int");

                    b.Property<string>("ResolverType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ResolverUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ApprovalStageApproverRule");

                    b.HasIndex("ApprovalWorkflowStageId", "IsEnabled")
                        .HasDatabaseName("IX_ApprovalStageApproverRule_Stage");

                    b.ToTable("ApprovalStageApproverRule", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalStageApproverRule_ResolverType", "([ResolverType] IN ( N'User', N'Role', N'Capability', N'EmployeeManager', N'RequesterManager', N'LocationBranchAdmin', N'CustomEmail' ))");

                            t.HasCheckConstraint("CK_ApprovalStageApproverRule_Value", "( ([ResolverType] = N'User' AND [ResolverUserId] IS NOT NULL) OR ([ResolverType] = N'Role' AND [ResolverRoleId] IS NOT NULL) OR ([ResolverType] = N'Capability' AND [ResolverCapabilityName] IS NOT NULL) OR ([ResolverType] = N'EmployeeManager') OR ([ResolverType] = N'RequesterManager') OR ([ResolverType] = N'LocationBranchAdmin' AND [ResolverCapabilityName] IS NOT NULL) OR ([ResolverType] = N'CustomEmail' AND [ResolverEmail] IS NOT NULL) )");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ApprovalWorkflowDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_ApprovalWorkflowDefinition_IsDefault");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_ApprovalWorkflowDefinition_IsPublished");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("ServiceTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_ApprovalWorkflowDefinition");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("UX_ApprovalWorkflowDefinition_OneActiveDefault")
                        .HasFilter("[IsDefault] = 1 AND [IsActive] = 1");

                    b.HasIndex("WorkflowName", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ApprovalWorkflowDefinition_NameVersion");

                    b.HasIndex("ServiceTemplateId", "LocationId", "Priority", "EffectiveFromUtc")
                        .HasDatabaseName("IX_ApprovalWorkflowDefinition_Match")
                        .HasFilter("[IsActive] = 1 AND [IsPublished] = 1");

                    b.ToTable("ApprovalWorkflowDefinition", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalWorkflowDefinition_EffectiveRange", "([EffectiveToUtc] IS NULL OR [EffectiveFromUtc] IS NULL OR [EffectiveToUtc] > [EffectiveFromUtc])");

                            t.HasCheckConstraint("CK_ApprovalWorkflowDefinition_Priority", "([Priority] IS NULL OR [Priority] IN (N'Low', N'Medium', N'High', N'Critical'))");

                            t.HasCheckConstraint("CK_ApprovalWorkflowDefinition_Version", "([VersionNumber] > 0)");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ApprovalWorkflowStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDelegation")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_ApprovalWorkflowStage_AllowDelegation");

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ApprovalWorkflowId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DueAfterMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("EscalateAfterMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReminderAfterMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("ReminderRepeatMinutes")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ApprovalWorkflowStage");

                    b.HasIndex("ApprovalWorkflowId", "StageNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ApprovalWorkflowStage_Number");

                    b.ToTable("ApprovalWorkflowStage", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalWorkflowStage_Mode", "([ApprovalMode] IN (N'Any', N'All'))");

                            t.HasCheckConstraint("CK_ApprovalWorkflowStage_Number", "([StageNumber] > 0)");

                            t.HasCheckConstraint("CK_ApprovalWorkflowStage_Timers", "( ([DueAfterMinutes] IS NULL OR [DueAfterMinutes] > 0) AND ([ReminderAfterMinutes] IS NULL OR [ReminderAfterMinutes] > 0) AND ([ReminderRepeatMinutes] IS NULL OR [ReminderRepeatMinutes] > 0) AND ([EscalateAfterMinutes] IS NULL OR [EscalateAfterMinutes] >= 0) )");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.NewServiceRequestDetail", b =>
                {
                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RequestCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RequestSubCategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RequiredByDate")
                        .HasColumnType("date");

                    b.HasKey("ServiceRequestId")
                        .HasName("PK_NewServiceRequestDetail");

                    b.ToTable("NewServiceRequestDetail", "ServiceDesk");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.NewServiceRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Specification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_NewServiceRequestItem");

                    b.HasIndex("ServiceRequestId")
                        .HasDatabaseName("IX_NewServiceRequestItem_ServiceRequestId");

                    b.ToTable("NewServiceRequestItem", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_NewServiceRequestItem_PositiveQuantity", "([Quantity] > 0)");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestApprovalDecision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActedByEmailSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ActedByUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DecidedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("RequestApprovalParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_RequestApprovalDecision");

                    b.HasIndex("ClientDecisionId")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestApprovalDecision_ClientId");

                    b.HasIndex("RequestApprovalParticipantId")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestApprovalDecision_Participant");

                    b.ToTable("RequestApprovalDecision", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestApprovalDecision_Decision", "([Decision] IN (N'Approved', N'Rejected'))");

                            t.HasCheckConstraint("CK_RequestApprovalDecision_Source", "([Source] IN (N'Application', N'EmailLink', N'Api'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestApprovalInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApprovalWorkflowId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentStageNumber")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkflowNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RequestApprovalInstance");

                    b.HasIndex("ServiceRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestApprovalInstance_OnePending")
                        .HasFilter("[Status] = N'Pending'");

                    b.HasIndex("ServiceRequestId", "SubmittedOnUtc")
                        .HasDatabaseName("IX_RequestApprovalInstance_Request");

                    b.ToTable("RequestApprovalInstance", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestApprovalInstance_CurrentStage", "([CurrentStageNumber] IS NULL OR [CurrentStageNumber] > 0)");

                            t.HasCheckConstraint("CK_RequestApprovalInstance_Status", "([Status] IN (N'Pending', N'Approved', N'Rejected', N'Cancelled'))");

                            t.HasCheckConstraint("CK_RequestApprovalInstance_Version", "([WorkflowVersion] > 0)");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestApprovalParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApproverEmailSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ApproverNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ApproverRuleId")
                        .HasColumnType("int");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DelegatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelegatedToUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ParticipantStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("RequestApprovalStepId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RequestApprovalParticipant");

                    b.HasIndex("ApproverUserId", "ParticipantStatus", "RequestApprovalStepId")
                        .HasDatabaseName("IX_RequestApprovalParticipant_Inbox");

                    b.HasIndex("RequestApprovalStepId", "ApproverRuleId", "ApproverEmailSnapshot")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestApprovalParticipant_Resolved");

                    b.ToTable("RequestApprovalParticipant", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestApprovalParticipant_Identity", "([ApproverUserId] IS NOT NULL OR [ApproverEmployeeId] IS NOT NULL OR [ApproverEmailSnapshot] <> N'')");

                            t.HasCheckConstraint("CK_RequestApprovalParticipant_Status", "([ParticipantStatus] IN (N'Waiting', N'Pending', N'Approved', N'Rejected', N'Delegated', N'Cancelled'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestApprovalStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActivatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalModeSnapshot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ApprovalWorkflowStageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutcomeRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("RequestApprovalInstanceId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StageNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_RequestApprovalStep");

                    b.HasIndex("DueOnUtc")
                        .HasDatabaseName("IX_RequestApprovalStep_Due")
                        .HasFilter("[Status] = N'Pending'");

                    b.HasIndex("RequestApprovalInstanceId")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestApprovalStep_OnePending")
                        .HasFilter("[Status] = N'Pending'");

                    b.HasIndex("RequestApprovalInstanceId", "StageNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestApprovalStep_Number");

                    b.ToTable("RequestApprovalStep", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestApprovalStep_Activation", "([Status] IN (N'Waiting', N'Cancelled', N'Skipped') OR [ActivatedOnUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_RequestApprovalStep_Mode", "([ApprovalModeSnapshot] IN (N'Any', N'All'))");

                            t.HasCheckConstraint("CK_RequestApprovalStep_Number", "([StageNumber] > 0)");

                            t.HasCheckConstraint("CK_RequestApprovalStep_Status", "([Status] IN (N'Waiting', N'Pending', N'Approved', N'Rejected', N'Skipped', N'Cancelled'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("RequestEmailId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_RequestAttachment");

                    b.HasIndex("ServiceRequestId")
                        .HasDatabaseName("IX_RequestAttachment_ServiceRequestId");

                    b.ToTable("RequestAttachment", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestAttachment_Type", "([AttachmentType] IN (N'Requester', N'Resolution', N'Email'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_RequestCategory");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestCategory_Name");

                    b.ToTable("RequestCategory", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestCategory_CategoryType", "([CategoryType] IN (N'Service', N'Incident'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcAddresses")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("N'Outbound'", "DF_RequestEmail_Direction");

                    b.Property<long?>("EmailOutboxId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1", "DF_RequestEmail_IsHtml");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("QueuedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SentByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_RequestEmail");

                    b.HasIndex("ServiceRequestId", "QueuedOnUtc")
                        .HasDatabaseName("IX_RequestEmail_Request");

                    b.ToTable("RequestEmail", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestEmail_Direction", "([Direction] IN (N'Outbound', N'Inbound'))");

                            t.HasCheckConstraint("CK_RequestEmail_SentBy", "([Direction] = N'Inbound' OR [SentByUserId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_RequestEmail_Status", "([Status] IN (N'Queued', N'Sent', N'Failed'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Transition'", "DF_RequestHistory_EntryKind");

                    b.Property<string>("EntryText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_RequestHistory_IsInternal");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RequestEmailId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RequestHistory");

                    b.HasIndex("RequestEmailId")
                        .HasDatabaseName("IX_RequestHistory_RequestEmailId");

                    b.HasIndex("ServiceRequestId", "OccurredOnUtc")
                        .HasDatabaseName("IX_RequestHistory_Request");

                    b.ToTable("RequestHistory", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestHistory_EntryKind", "([EntryKind] IN (N'Transition', N'Note', N'Email', N'Automation', N'Sla', N'Escalation'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CountsTechnicianTime")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_RequestStatus_CountsTechnicianTime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosedState")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SlaClockBehaviour")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("N'Running'", "DF_RequestStatus_SlaClockBehaviour");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_RequestStatus");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestStatus_Name");

                    b.ToTable("RequestStatus", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_RequestStatus_SlaClockBehaviour", "([SlaClockBehaviour] IN (N'Running', N'Paused', N'Stopped'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_RequestSubCategory");

                    b.HasIndex("RequestCategoryId", "SubCategoryName")
                        .IsUnique()
                        .HasDatabaseName("UX_RequestSubCategory_Name");

                    b.ToTable("RequestSubCategory", "ServiceDesk");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("FirstResponseOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsScheduledHold")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_ServiceRequest_IsScheduledHold");

                    b.Property<bool>("IsSlaOverdue")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_ServiceRequest_IsSlaOverdue");

                    b.Property<bool>("IsSlaPaused")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_ServiceRequest_IsSlaPaused");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ManualAssetText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextOperationalStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OnBehalfOfEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RequestCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("RequestKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestSubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ResolutionConsumedMinutes")
                        .HasColumnType("int")
                        .HasDefaultValueSql("0", "DF_ServiceRequest_ResolutionConsumedMinutes");

                    b.Property<DateTime?>("ResolutionDueOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDueOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponseElapsedMinutes")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScheduleHoldReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ServiceTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SlaLastCalculatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlaPausedMinutes")
                        .HasColumnType("int")
                        .HasDefaultValueSql("0", "DF_ServiceRequest_SlaPausedMinutes");

                    b.Property<int?>("SlaPolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SlaStartOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TechnicianWorkingMinutes")
                        .HasColumnType("int")
                        .HasDefaultValueSql("0", "DF_ServiceRequest_TechnicianWorkingMinutes");

                    b.HasKey("Id")
                        .HasName("PK_ServiceRequest");

                    b.HasIndex("NextOperationalStartUtc")
                        .HasDatabaseName("IX_ServiceRequest_ScheduledIntake")
                        .HasFilter("[IsScheduledHold] = 1");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceRequest_Number");

                    b.HasIndex("RequestedByEmployeeId")
                        .HasDatabaseName("IX_ServiceRequest_Requester");

                    b.HasIndex("AssignedTeamId", "RequestStatusId")
                        .HasDatabaseName("IX_ServiceRequest_AssignedTeam");

                    b.HasIndex("IsSlaOverdue", "ResolutionDueOnUtc")
                        .HasDatabaseName("IX_ServiceRequest_SlaQueue")
                        .HasFilter("[ClosedOnUtc] IS NULL");

                    b.HasIndex("RequestStatusId", "LocationId", "Priority")
                        .HasDatabaseName("IX_ServiceRequest_Queue");

                    b.ToTable("ServiceRequest", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceRequest_Kind", "([RequestKind] IN (N'SupportTicket', N'AssetIssue', N'NewService'))");

                            t.HasCheckConstraint("CK_ServiceRequest_Priority", "([Priority] IN (N'Low', N'Medium', N'High', N'Critical'))");

                            t.HasCheckConstraint("CK_ServiceRequest_ScheduledHold", "([IsScheduledHold] = 0 OR [NextOperationalStartUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ServiceRequest_SlaMinutes", "([ResolutionConsumedMinutes] >= 0 AND [TechnicianWorkingMinutes] >= 0 AND [SlaPausedMinutes] >= 0 AND ([ResponseElapsedMinutes] IS NULL OR [ResponseElapsedMinutes] >= 0))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ServiceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultPriority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("DefaultSupportTeamId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionTemplate")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("RequestKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RequestSubCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresAsset")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_ServiceTemplate_RequiresAsset");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_ServiceTemplate");

                    b.HasIndex("TemplateName")
                        .IsUnique()
                        .HasDatabaseName("UX_ServiceTemplate_Name");

                    b.ToTable("ServiceTemplate", "ServiceDesk", t =>
                        {
                            t.HasCheckConstraint("CK_ServiceTemplate_Kind", "([RequestKind] IN (N'SupportTicket', N'AssetIssue', N'NewService'))");

                            t.HasCheckConstraint("CK_ServiceTemplate_Priority", "([DefaultPriority] IN (N'Low', N'Medium', N'High', N'Critical'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.SupportTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefaultTeam")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_SupportTeam_IsDefaultTeam");

                    b.Property<string>("MailboxAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_SupportTeam");

                    b.HasIndex("IsDefaultTeam")
                        .IsUnique()
                        .HasDatabaseName("UX_SupportTeam_OneDefault")
                        .HasFilter("[IsDefaultTeam] = 1");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("IX_SupportTeam_RegionId");

                    b.HasIndex("TeamName")
                        .IsUnique()
                        .HasDatabaseName("UX_SupportTeam_Name");

                    b.ToTable("SupportTeam", "ServiceDesk");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.SupportTeamMember", b =>
                {
                    b.Property<int>("SupportTeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("AddedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLead")
                        .HasColumnType("bit");

                    b.HasKey("SupportTeamId", "UserId")
                        .HasName("PK_SupportTeamMember");

                    b.ToTable("SupportTeamMember", "ServiceDesk");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ApprovalNotificationLog", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestApprovalInstance", null)
                        .WithMany()
                        .HasForeignKey("RequestApprovalInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalNotificationLog_RequestApprovalInstance_RequestApprovalInstanceId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestApprovalParticipant", null)
                        .WithMany()
                        .HasForeignKey("RequestApprovalParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ApprovalNotificationLog_RequestApprovalParticipant_RequestApprovalParticipantId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestApprovalStep", null)
                        .WithMany()
                        .HasForeignKey("RequestApprovalStepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ApprovalNotificationLog_RequestApprovalStep_RequestApprovalStepId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ApprovalStageApproverRule", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ApprovalWorkflowStage", null)
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalStageApproverRule_ApprovalWorkflowStage_ApprovalWorkflowStageId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ApprovalWorkflowDefinition", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ServiceTemplate", null)
                        .WithMany()
                        .HasForeignKey("ServiceTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ApprovalWorkflowDefinition_ServiceTemplate_ServiceTemplateId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ApprovalWorkflowStage", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ApprovalWorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalWorkflowStage_ApprovalWorkflowDefinition_ApprovalWorkflowId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.NewServiceRequestDetail", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestCategory", null)
                        .WithMany()
                        .HasForeignKey("RequestCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NewServiceRequestDetail_RequestCategory_RequestCategoryId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NewServiceRequestDetail_ServiceRequest_ServiceRequestId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestSubCategory", null)
                        .WithMany()
                        .HasForeignKey("RequestSubCategoryId", "RequestCategoryId")
                        .HasPrincipalKey("Id", "RequestCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_NewServiceRequestDetail_RequestSubCategory_Category");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.NewServiceRequestItem", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NewServiceRequestItem_ServiceRequest_ServiceRequestId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestApprovalDecision", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestApprovalParticipant", null)
                        .WithMany()
                        .HasForeignKey("RequestApprovalParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RequestApprovalDecision_RequestApprovalParticipant_RequestApprovalParticipantId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestApprovalInstance", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ApprovalWorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RequestApprovalInstance_ApprovalWorkflowDefinition_ApprovalWorkflowId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RequestApprovalInstance_ServiceRequest_ServiceRequestId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestApprovalParticipant", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ApprovalStageApproverRule", null)
                        .WithMany()
                        .HasForeignKey("ApproverRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RequestApprovalParticipant_ApprovalStageApproverRule_ApproverRuleId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestApprovalStep", null)
                        .WithMany()
                        .HasForeignKey("RequestApprovalStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RequestApprovalParticipant_RequestApprovalStep_RequestApprovalStepId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestApprovalStep", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ApprovalWorkflowStage", null)
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowStageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_RequestApprovalStep_ApprovalWorkflowStage_ApprovalWorkflowStageId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestApprovalInstance", null)
                        .WithMany()
                        .HasForeignKey("RequestApprovalInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RequestApprovalStep_RequestApprovalInstance_RequestApprovalInstanceId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestAttachment", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestEmail", null)
                        .WithMany()
                        .HasForeignKey("RequestEmailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RequestAttachment_RequestEmail_RequestEmailId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RequestAttachment_ServiceRequest_ServiceRequestId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestEmail", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RequestEmail_ServiceRequest_ServiceRequestId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestHistory", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestEmail", null)
                        .WithMany()
                        .HasForeignKey("RequestEmailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_RequestHistory_RequestEmail_RequestEmailId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RequestHistory_ServiceRequest_ServiceRequestId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.RequestSubCategory", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestCategory", null)
                        .WithMany()
                        .HasForeignKey("RequestCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RequestSubCategory_RequestCategory_RequestCategoryId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ServiceRequest", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.SupportTeam", null)
                        .WithMany()
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ServiceRequest_SupportTeam_AssignedTeamId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestCategory", null)
                        .WithMany()
                        .HasForeignKey("RequestCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ServiceRequest_RequestCategory_RequestCategoryId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestStatus", null)
                        .WithMany()
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceRequest_RequestStatus_RequestStatusId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestSubCategory", null)
                        .WithMany()
                        .HasForeignKey("RequestSubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ServiceRequest_RequestSubCategory_RequestSubCategoryId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.ServiceTemplate", null)
                        .WithMany()
                        .HasForeignKey("ServiceTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ServiceRequest_ServiceTemplate_ServiceTemplateId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.ServiceTemplate", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.SupportTeam", null)
                        .WithMany()
                        .HasForeignKey("DefaultSupportTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ServiceTemplate_SupportTeam_DefaultSupportTeamId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestCategory", null)
                        .WithMany()
                        .HasForeignKey("RequestCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ServiceTemplate_RequestCategory_RequestCategoryId");

                    b.HasOne("AMS.Modules.ServiceDesk.Domain.RequestSubCategory", null)
                        .WithMany()
                        .HasForeignKey("RequestSubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ServiceTemplate_RequestSubCategory_RequestSubCategoryId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceDesk.Domain.SupportTeamMember", b =>
                {
                    b.HasOne("AMS.Modules.ServiceDesk.Domain.SupportTeam", null)
                        .WithMany()
                        .HasForeignKey("SupportTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SupportTeamMember_SupportTeam_SupportTeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
