using Microsoft.EntityFrameworkCore;

namespace AMS.PersistenceGates.Tests;

/// <summary>A system-versioned row carrying R2-22's token.</summary>
public sealed class StampedAsset
{
    public int Id { get; set; }

    public string Name { get; set; } = string.Empty;

    /// <summary>R2-22. Regenerated by the application on every update.</summary>
    public Guid ConcurrencyStamp { get; set; }
}

/// <summary>
/// Maps <see cref="StampedAsset"/> the way every one of the five
/// system-versioned tables is mapped after R2-22.
/// </summary>
public sealed class StampedContext(DbContextOptions<StampedContext> options) : DbContext(options)
{
    public DbSet<StampedAsset> Assets => Set<StampedAsset>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var entity = modelBuilder.Entity<StampedAsset>();

        entity.ToTable("StampedAsset", "Assets", table => table.IsTemporal(temporal =>
        {
            temporal.HasPeriodStart("SysStartTime");
            temporal.HasPeriodEnd("SysEndTime");
            temporal.UseHistoryTable("StampedAssetHistory", "Assets");
        }));

        entity.Property(x => x.Name).HasMaxLength(100).IsRequired();

        // The token. Note what is NOT here: no period column is nominated.
        entity.Property(x => x.ConcurrencyStamp).IsConcurrencyToken();
    }

    /// <summary>
    /// Stands in for the audit interceptor: re-stamp every modified row so the
    /// token changes because the APPLICATION changed the row.
    /// </summary>
    public override int SaveChanges()
    {
        Restamp();
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
    {
        Restamp();
        return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
    }

    private void Restamp()
    {
        foreach (var entry in ChangeTracker.Entries<StampedAsset>())
        {
            if (entry.State is EntityState.Added or EntityState.Modified)
            {
                entry.Entity.ConcurrencyStamp = Guid.NewGuid();
            }
        }
    }
}

/// <summary>
/// GATE C — proves R2-22 actually fixed what Gate A found.
/// </summary>
/// <remarks>
/// Gate A showed <c>SysStartTime</c> failing to detect a concurrent write
/// whenever both writes landed inside one system-clock tick, losing one
/// silently. R2-22 replaced it with an application-generated
/// <c>ConcurrencyStamp</c>. A replacement is worth no more than the evidence
/// for it, so this runs the same scenario with NO delays at all — the
/// conditions under which the old mechanism failed — and requires detection
/// every time.
/// </remarks>
[Collection(nameof(SqlServerCollectionDefinition))]
public sealed class GateCConcurrencyStamp(SqlServerFixture fixture)
{
    [Fact]
    public async Task A_stale_stamp_is_rejected_with_no_delay_anywhere()
    {
        var id = await SeedAsync("Laptop");

        await using var first = NewContext();
        await using var second = NewContext();

        var a = await first.Assets.SingleAsync(x => x.Id == id);
        var b = await second.Assets.SingleAsync(x => x.Id == id);

        a.Name = "written by the first writer";
        await first.SaveChangesAsync();

        b.Name = "written by the second writer";

        // No Task.Delay. This is precisely where SysStartTime let the write
        // through and lost the first writer's change (Gate A, Test1b).
        await Should.ThrowAsync<DbUpdateConcurrencyException>(() => second.SaveChangesAsync());

        var survivor = await fixture.ScalarAsync<string>(
            $"SELECT [Name] FROM [Assets].[StampedAsset] WHERE [Id] = {id};");

        survivor.ShouldBe("written by the first writer", "the first writer's change must survive");
    }

    [Fact]
    public async Task Detection_does_not_depend_on_the_clock()
    {
        // Twenty back-to-back rounds. Gate A's probe showed 20 of 20
        // insert-then-update pairs sharing a SysStartTime; if this token had
        // the same weakness, this loop would expose it.
        for (var round = 0; round < 20; round++)
        {
            var id = await SeedAsync($"Asset {round}");

            await using var first = NewContext();
            await using var second = NewContext();

            var a = await first.Assets.SingleAsync(x => x.Id == id);
            var b = await second.Assets.SingleAsync(x => x.Id == id);

            a.Name = $"first {round}";
            await first.SaveChangesAsync();

            b.Name = $"second {round}";
            await Should.ThrowAsync<DbUpdateConcurrencyException>(() => second.SaveChangesAsync());
        }
    }

    [Fact]
    public async Task The_stamp_moves_on_every_update_and_the_tracked_entity_keeps_up()
    {
        var id = await SeedAsync("Monitor");

        await using var context = NewContext();
        var asset = await context.Assets.SingleAsync(x => x.Id == id);
        var before = asset.ConcurrencyStamp;

        asset.Name = "Monitor (renamed)";
        await context.SaveChangesAsync();

        asset.ConcurrencyStamp.ShouldNotBe(before);

        // A second save in the same context must still work: this is the
        // false-412 failure mode Gate A test 3 was written to catch.
        asset.Name = "Monitor (renamed twice)";
        var affected = await context.SaveChangesAsync();

        affected.ShouldBe(1);
    }

    [Fact]
    public async Task History_is_still_recorded()
    {
        // SysStartTime keeps its real job. Two edits separated enough for SQL
        // Server to keep both versions.
        var id = await SeedAsync("Printer");

        await using (var context = NewContext())
        {
            var asset = await context.Assets.SingleAsync(x => x.Id == id);
            asset.Name = "Printer v2";
            await context.SaveChangesAsync();
        }

        await Task.Delay(TimeSpan.FromMilliseconds(50));

        await using (var context = NewContext())
        {
            var asset = await context.Assets.SingleAsync(x => x.Id == id);
            asset.Name = "Printer v3";
            await context.SaveChangesAsync();
        }

        var versions = await fixture.ScalarAsync<int>(
            $"SELECT COUNT(*) FROM [Assets].[StampedAssetHistory] WHERE [Id] = {id};");

        versions.ShouldBeGreaterThan(0, "system versioning must still record prior versions");
    }

    private StampedContext NewContext() =>
        new(new DbContextOptionsBuilder<StampedContext>()
            .UseSqlServer(fixture.ConnectionString)
            .Options);

    private async Task<int> SeedAsync(string name)
    {
        await using var context = NewContext();
        var asset = new StampedAsset { Name = name };
        context.Assets.Add(asset);
        await context.SaveChangesAsync();
        return asset.Id;
    }
}
