// <auto-generated />
using System;
using AMS.Modules.Verification.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.Verification.Persistence.Migrations
{
    [DbContext(typeof(VerificationDbContext))]
    partial class VerificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Verification")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.Verification.Domain.PhysicalVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClientCaptureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CountedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExpectedQuantitySnapshot")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("GpsLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("GpsLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("HasQrMismatch")
                        .HasColumnType("bit");

                    b.Property<int?>("HolderEmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBulkCount")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0", "DF_PhysicalVerification_IsBulkCount");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("PhysicalVerificationCycleId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScannedQrValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("SerialVerified")
                        .HasColumnType("bit");

                    b.Property<int?>("StatusUpdatedToId")
                        .HasColumnType("int");

                    b.Property<int>("VerifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VerifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkingCondition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_PhysicalVerification");

                    b.HasIndex("ClientCaptureId")
                        .IsUnique()
                        .HasDatabaseName("UX_PhysicalVerification_ClientCapture")
                        .HasFilter("[ClientCaptureId] IS NOT NULL");

                    b.HasIndex("LocationId", "WorkingCondition")
                        .HasDatabaseName("IX_PhysicalVerification_Exceptions");

                    b.HasIndex("PhysicalVerificationCycleId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_PhysicalVerification_OnePerUnitAssetPerCycle")
                        .HasFilter("[IsBulkCount] = 0");

                    b.HasIndex("PhysicalVerificationCycleId", "AssetId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_PhysicalVerification_OneBulkCountPerPlacePerCycle")
                        .HasFilter("[IsBulkCount] = 1");

                    b.ToTable("PhysicalVerification", "Verification", t =>
                        {
                            t.HasCheckConstraint("CK_PhysicalVerification_BulkHasCount", "([IsBulkCount] = 0 OR [CountedQuantity] IS NOT NULL)");

                            t.HasCheckConstraint("CK_PhysicalVerification_Condition", "([WorkingCondition] IN (N'Good', N'MinorDamage', N'Damaged', N'NotWorking', N'Missing'))");

                            t.HasCheckConstraint("CK_PhysicalVerification_CountNonNegative", "([CountedQuantity] IS NULL OR [CountedQuantity] >= 0)");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Verification.Domain.PhysicalVerificationAssignment", b =>
                {
                    b.Property<int>("PhysicalVerificationCycleId")
                        .HasColumnType("int");

                    b.Property<int>("AuditorUserId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AssignedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PhysicalVerificationCycleId", "AuditorUserId")
                        .HasName("PK_PhysicalVerificationAssignment");

                    b.HasIndex("AuditorUserId")
                        .HasDatabaseName("IX_PhysicalVerificationAssignment_AuditorUserId");

                    b.ToTable("PhysicalVerificationAssignment", "Verification");
                });

            modelBuilder.Entity("AMS.Modules.Verification.Domain.PhysicalVerificationCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalAssetCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_PhysicalVerificationCycle");

                    b.HasIndex("CycleName")
                        .IsUnique()
                        .HasDatabaseName("UX_PhysicalVerificationCycle_Name");

                    b.ToTable("PhysicalVerificationCycle", "Verification");
                });

            modelBuilder.Entity("AMS.Modules.Verification.Domain.PhysicalVerificationCycleLocation", b =>
                {
                    b.Property<int>("PhysicalVerificationCycleId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.HasKey("PhysicalVerificationCycleId", "BranchId")
                        .HasName("PK_PhysicalVerificationCycleLocation");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_PhysicalVerificationCycleLocation_BranchId");

                    b.ToTable("PhysicalVerificationCycleLocation", "Verification");
                });

            modelBuilder.Entity("AMS.Modules.Verification.Domain.PhysicalVerification", b =>
                {
                    b.HasOne("AMS.Modules.Verification.Domain.PhysicalVerificationCycle", null)
                        .WithMany()
                        .HasForeignKey("PhysicalVerificationCycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PhysicalVerification_PhysicalVerificationCycle_PhysicalVerificationCycleId");
                });

            modelBuilder.Entity("AMS.Modules.Verification.Domain.PhysicalVerificationAssignment", b =>
                {
                    b.HasOne("AMS.Modules.Verification.Domain.PhysicalVerificationCycle", null)
                        .WithMany()
                        .HasForeignKey("PhysicalVerificationCycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PhysicalVerificationAssignment_Cycle_PhysicalVerificationCycleId");
                });

            modelBuilder.Entity("AMS.Modules.Verification.Domain.PhysicalVerificationCycleLocation", b =>
                {
                    b.HasOne("AMS.Modules.Verification.Domain.PhysicalVerificationCycle", null)
                        .WithMany()
                        .HasForeignKey("PhysicalVerificationCycleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PhysicalVerificationCycleLocation_Cycle_PhysicalVerificationCycleId");
                });
#pragma warning restore 612, 618
        }
    }
}
