// <auto-generated />
using System;
using AMS.Modules.Contracts.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.Contracts.Persistence.Migrations
{
    [DbContext(typeof(ContractsDbContext))]
    [Migration("20260812092117_20260812_Contracts_NamedDefaultConstraints")]
    partial class _20260812_Contracts_NamedDefaultConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Contracts")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()", "DF_Contract_ConcurrencyStamp");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("ContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("LicenseKeyEncrypted")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("LicensedSeats")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RenewalCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Contract");

                    b.HasIndex("ContractNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Contract_Number");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_Contract_EndDate");

                    b.ToTable("Contract", "Contracts", t =>
                        {
                            t.HasCheckConstraint("CK_Contract_Window", "([EndDate] >= [StartDate])");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ContractHistory", "Contracts");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.ContractAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LinkedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_ContractAsset");

                    b.HasIndex("ContractId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_ContractAsset_NoDuplicates");

                    b.ToTable("ContractAsset", "Contracts");
                });

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.ContractDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_ContractDocument");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("IX_ContractDocument_ContractId");

                    b.ToTable("ContractDocument", "Contracts");
                });

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.ContractReminderLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("DaysBeforeExpiry")
                        .HasColumnType("int");

                    b.Property<long?>("EmailOutboxId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ExpiryDateSnapshot")
                        .HasColumnType("date");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Queued'", "DF_ContractReminderLog_Outcome");

                    b.Property<DateOnly>("SentOnDate")
                        .HasColumnType("date");

                    b.Property<string>("SentTo")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id")
                        .HasName("PK_ContractReminderLog");

                    b.HasIndex("ContractId", "DaysBeforeExpiry", "ExpiryDateSnapshot")
                        .IsUnique()
                        .HasDatabaseName("UX_ContractReminderLog_OncePerThreshold")
                        .HasFilter("[Outcome] <> N'Failed'");

                    b.ToTable("ContractReminderLog", "Contracts", t =>
                        {
                            t.HasCheckConstraint("CK_ContractReminderLog_Outcome", "([Outcome] IN (N'Queued', N'Sent', N'Failed'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.ContractReminderSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Email'", "DF_ContractReminderSetting_Channel");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysBeforeExpiry")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recipients")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_ContractReminderSetting");

                    b.HasIndex("DaysBeforeExpiry")
                        .IsUnique()
                        .HasDatabaseName("UX_ContractReminderSetting_Default")
                        .HasFilter("[ContractId] IS NULL");

                    b.HasIndex("ContractId", "DaysBeforeExpiry")
                        .IsUnique()
                        .HasDatabaseName("UX_ContractReminderSetting_PerContract")
                        .HasFilter("[ContractId] IS NOT NULL");

                    b.ToTable("ContractReminderSetting", "Contracts", t =>
                        {
                            t.HasCheckConstraint("CK_ContractReminderSetting_Channel", "([Channel] IN (N'Email', N'InApp', N'Both'))");

                            t.HasCheckConstraint("CK_ContractReminderSetting_Days", "([DaysBeforeExpiry] BETWEEN 1 AND 365)");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.ContractAsset", b =>
                {
                    b.HasOne("AMS.Modules.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContractAsset_Contract_ContractId");
                });

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.ContractDocument", b =>
                {
                    b.HasOne("AMS.Modules.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContractDocument_Contract_ContractId");
                });

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.ContractReminderLog", b =>
                {
                    b.HasOne("AMS.Modules.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContractReminderLog_Contract_ContractId");
                });

            modelBuilder.Entity("AMS.Modules.Contracts.Domain.ContractReminderSetting", b =>
                {
                    b.HasOne("AMS.Modules.Contracts.Domain.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ContractReminderSetting_Contract_ContractId");
                });
#pragma warning restore 612, 618
        }
    }
}
