// <auto-generated />
using System;
using AMS.Modules.DataImport.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.DataImport.Persistence.Migrations
{
    [DbContext(typeof(DataImportDbContext))]
    [Migration("20260812091700_20260812_DataImport_RecoveredDefaults")]
    partial class _20260812_DataImport_RecoveredDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DataImport")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.DataImport.Domain.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("0");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ImportedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SucceededRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("0");

                    b.Property<int>("TotalRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id")
                        .HasName("PK_ImportBatch");

                    b.HasIndex("BatchNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ImportBatch_Number");

                    b.HasIndex("ImportType", "StartedOnUtc")
                        .HasDatabaseName("IX_ImportBatch_TypeRecent");

                    b.ToTable("ImportBatch", "DataImport", t =>
                        {
                            t.HasCheckConstraint("CK_ImportBatch_Counts", "([TotalRows] >= 0 AND [SucceededRows] >= 0 AND [FailedRows] >= 0 AND [SucceededRows] + [FailedRows] <= [TotalRows])");

                            t.HasCheckConstraint("CK_ImportBatch_Status", "([Status] IN (N'Running', N'Rehearsed', N'Committed', N'Failed', N'Cancelled'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.DataImport.Domain.ImportError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ColumnName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("RawValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RecordedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ImportError");

                    b.HasIndex("ImportBatchId", "RowNumber")
                        .HasDatabaseName("IX_ImportError_Batch");

                    b.ToTable("ImportError", "DataImport", t =>
                        {
                            t.HasCheckConstraint("CK_ImportError_RowNumber", "([RowNumber] > 0)");
                        });
                });

            modelBuilder.Entity("AMS.Modules.DataImport.Domain.ImportError", b =>
                {
                    b.HasOne("AMS.Modules.DataImport.Domain.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ImportError_ImportBatch_ImportBatchId");
                });
#pragma warning restore 612, 618
        }
    }
}
