// <auto-generated />
using System;
using AMS.Modules.Transfers.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.Transfers.Persistence.Migrations
{
    [DbContext(typeof(TransfersDbContext))]
    [Migration("20260812063338_20260812_Transfers_Initial")]
    partial class _20260812_Transfers_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Transfers")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.Transfers.Domain.AssetTransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromCostCenter")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("FromDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("FromEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MovementId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SapSyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToCostCenter")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("ToDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ToEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ToLocationId")
                        .HasColumnType("int");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_AssetTransferRequest");

                    b.HasIndex("SapSyncStatus")
                        .HasDatabaseName("IX_AssetTransferRequest_SapPending")
                        .HasFilter("[SapSyncStatus] = 'Pending'");

                    b.HasIndex("Status", "FromLocationId")
                        .HasDatabaseName("IX_AssetTransferRequest_Queue");

                    b.ToTable("AssetTransferRequest", "Transfers", t =>
                        {
                            t.HasCheckConstraint("CK_AssetTransferRequest_TypePair", "(([TransferType] = 'Employee' AND [ToEmployeeId] IS NOT NULL) OR ([TransferType] = 'Department' AND [ToDepartmentId] IS NOT NULL) OR ([TransferType] = 'Branch' AND [ToLocationId] IS NOT NULL) OR ([TransferType] = 'CostCenter' AND [ToCostCenter] IS NOT NULL))");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
