import { bootstrapApplication } from '@angular/platform-browser';
import config from 'devextreme/core/config';

import { appConfig } from './app/app.config';
import { App } from './app/app';
import { licenseKey } from './devextreme-license';

/*
 * DevExtreme licence, applied before anything renders — a component created
 * before this runs shows the evaluation banner.
 *
 * `devextreme-license.ts` is generated by the `devextreme-license` CLI from the
 * DevExpress licence registered on the machine, and is gitignored: the runtime
 * key does not belong in source control. The prestart and prebuild npm scripts
 * regenerate it, so a fresh clone needs the machine licence but no manual step.
 */
config({ licenseKey });

bootstrapApplication(App, appConfig).catch((err) => console.error(err));
