// <auto-generated />
using System;
using AMS.Modules.Movements.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.Movements.Persistence.Migrations
{
    [DbContext(typeof(MovementsDbContext))]
    [Migration("20260812091341_20260812_Movements_Revision3")]
    partial class _20260812_Movements_Revision3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Movements")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.Movements.Domain.AssetMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("ChallanNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CourierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("HandoverId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MovementBatchId")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValueSql("1");

                    b.Property<string>("ReceiptRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("ShippedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ToLocationId")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK_AssetMovement");

                    b.HasIndex("HandoverId")
                        .HasDatabaseName("IX_AssetMovement_Handover");

                    b.HasIndex("MovementBatchId")
                        .HasDatabaseName("IX_AssetMovement_Batch");

                    b.HasIndex("Status", "ToLocationId")
                        .HasDatabaseName("IX_AssetMovement_Incoming");

                    b.ToTable("AssetMovement", "Movements", t =>
                        {
                            t.HasCheckConstraint("CK_AssetMovement_DifferentBranches", "([FromLocationId] <> [ToLocationId])");

                            t.HasCheckConstraint("CK_AssetMovement_QuantityPositive", "([Quantity] > 0)");

                            t.HasCheckConstraint("CK_AssetMovement_ReceiptPair", "(([Status] = N'Received' AND [ReceivedOnUtc] IS NOT NULL) OR ([Status] <> N'Received' AND [ReceivedOnUtc] IS NULL))");

                            t.HasCheckConstraint("CK_AssetMovement_Status", "([Status] IN (N'InTransit', N'Received', N'Cancelled'))");

                            t.HasCheckConstraint("CK_AssetMovement_Type", "([MovementType] IN (N'Transfer', N'HandoverToHO'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Movements.Domain.MovementBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ChallanNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CourierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispatchedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReceivedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("ShippedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToLocationId")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK_MovementBatch");

                    b.HasIndex("BatchNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_MovementBatch_Number");

                    b.HasIndex("ToLocationId", "ShippedOnUtc")
                        .HasDatabaseName("IX_MovementBatch_Open")
                        .HasFilter("[ReceivedOnUtc] IS NULL");

                    b.ToTable("MovementBatch", "Movements", t =>
                        {
                            t.HasCheckConstraint("CK_MovementBatch_DifferentBranches", "([FromLocationId] <> [ToLocationId])");

                            t.HasCheckConstraint("CK_MovementBatch_PositiveCount", "([ItemCount] > 0)");

                            t.HasCheckConstraint("CK_MovementBatch_Type", "([MovementType] IN (N'Transfer', N'HandoverToHO'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.Movements.Domain.AssetMovement", b =>
                {
                    b.HasOne("AMS.Modules.Movements.Domain.MovementBatch", null)
                        .WithMany()
                        .HasForeignKey("MovementBatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_AssetMovement_MovementBatch_MovementBatchId");
                });
#pragma warning restore 612, 618
        }
    }
}
