// <auto-generated />
using System;
using AMS.Modules.ServiceLevel.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS.Modules.ServiceLevel.Persistence.Migrations
{
    [DbContext(typeof(ServiceLevelDbContext))]
    [Migration("20260812063342_20260812_ServiceLevel_Initial")]
    partial class _20260812_ServiceLevel_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ServiceLevel")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.HolidayCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AppliesToAllLocations")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HolidayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("HolidayYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurringAnnually")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("RecurrenceDay")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RecurrenceMonth")
                        .HasColumnType("tinyint");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id")
                        .HasName("PK_HolidayCalendar");

                    b.HasIndex("HolidayYear", "HolidayDate")
                        .HasDatabaseName("IX_HolidayCalendar_YearDate")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("RecurrenceMonth", "RecurrenceDay")
                        .HasDatabaseName("IX_HolidayCalendar_Recurring")
                        .HasFilter("[IsRecurringAnnually] = 1");

                    b.ToTable("HolidayCalendar", "ServiceLevel", t =>
                        {
                            t.HasCheckConstraint("CK_HolidayCalendar_Recurrence", "([IsRecurringAnnually] = 0 OR ([RecurrenceMonth] BETWEEN 1 AND 12 AND [RecurrenceDay] >= 1 AND [RecurrenceDay] <= CASE WHEN [RecurrenceMonth] IN (4, 6, 9, 11) THEN 30 WHEN [RecurrenceMonth] = 2 THEN 29 ELSE 31 END))");

                            t.HasCheckConstraint("CK_HolidayCalendar_Type", "([HolidayType] IN (N'Government', N'Festival', N'Regional', N'Optional'))");

                            t.HasCheckConstraint("CK_HolidayCalendar_Year", "([HolidayYear] BETWEEN 2000 AND 2100)");

                            t.HasCheckConstraint("CK_HolidayCalendar_YearMatchesDate", "([HolidayYear] = YEAR([HolidayDate]))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.HolidayLocation", b =>
                {
                    b.Property<int>("HolidayCalendarId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("HolidayCalendarId", "LocationId")
                        .HasName("PK_HolidayLocation");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("IX_HolidayLocation_LocationId");

                    b.ToTable("HolidayLocation", "ServiceLevel");
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.LocationOperationalDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("BreakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("BreakStartTime")
                        .HasColumnType("time");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<int>("LocationOperationalHourId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK_LocationOperationalDay");

                    b.HasIndex("LocationOperationalHourId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("UX_LocationOperationalDay_Day");

                    b.ToTable("LocationOperationalDay", "ServiceLevel", t =>
                        {
                            t.HasCheckConstraint("CK_LocationOperationalDay_CustomBreak", "(([BreakStartTime] IS NULL AND [BreakEndTime] IS NULL) OR ([BreakStartTime] IS NOT NULL AND [BreakEndTime] IS NOT NULL AND [BreakEndTime] > [BreakStartTime]))");

                            t.HasCheckConstraint("CK_LocationOperationalDay_CustomTimes", "([DayType] <> N'Custom' OR ([StartTime] IS NOT NULL AND [EndTime] IS NOT NULL AND [EndTime] > [StartTime]))");

                            t.HasCheckConstraint("CK_LocationOperationalDay_DayOfWeek", "([DayOfWeek] BETWEEN 0 AND 6)");

                            t.HasCheckConstraint("CK_LocationOperationalDay_DayType", "([DayType] IN (N'Standard', N'Custom', N'TwentyFourHour'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.LocationOperationalHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("BreakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("BreakStartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeferFinalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("30");

                    b.Property<bool>("DeferNewTicketsOnFriday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRoundTheClock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StandardEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StandardStartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime");

                    b.HasKey("Id")
                        .HasName("PK_LocationOperationalHour");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasDatabaseName("UX_LocationOperationalHour_Location");

                    b.ToTable("LocationOperationalHour", "ServiceLevel", t =>
                        {
                            t.HasCheckConstraint("CK_LocationOperationalHour_BreakInside", "([IsRoundTheClock] = 1 OR [BreakStartTime] IS NULL OR ([BreakStartTime] >= [StandardStartTime] AND [BreakEndTime] <= [StandardEndTime]))");

                            t.HasCheckConstraint("CK_LocationOperationalHour_BreakPair", "(([BreakStartTime] IS NULL AND [BreakEndTime] IS NULL) OR ([BreakStartTime] IS NOT NULL AND [BreakEndTime] IS NOT NULL AND [BreakEndTime] > [BreakStartTime]))");

                            t.HasCheckConstraint("CK_LocationOperationalHour_DeferMinutes", "([DeferFinalMinutes] BETWEEN 0 AND 480)");

                            t.HasCheckConstraint("CK_LocationOperationalHour_Window", "([IsRoundTheClock] = 1 OR [StandardEndTime] > [StandardStartTime])");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("LocationOperationalHourHistory", "ServiceLevel");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.LocationSaturdayRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsWorking")
                        .HasColumnType("bit");

                    b.Property<int>("LocationOperationalHourId")
                        .HasColumnType("int");

                    b.Property<byte>("Occurrence")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK_LocationSaturdayRule");

                    b.HasIndex("LocationOperationalHourId", "Occurrence")
                        .IsUnique()
                        .HasDatabaseName("UX_LocationSaturdayRule_Occurrence");

                    b.ToTable("LocationSaturdayRule", "ServiceLevel", t =>
                        {
                            t.HasCheckConstraint("CK_LocationSaturdayRule_Occurrence", "([Occurrence] BETWEEN 1 AND 5)");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.SlaEscalation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientAddress")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SlaPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("ThresholdPercent")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_SlaEscalation");

                    b.HasIndex("SlaPolicyId", "EscalationType", "Level")
                        .IsUnique()
                        .HasDatabaseName("UX_SlaEscalation_PolicyTypeLevel");

                    b.ToTable("SlaEscalation", "ServiceLevel", t =>
                        {
                            t.HasCheckConstraint("CK_SlaEscalation_Channel", "([Channel] IN (N'Email', N'InApp', N'Both'))");

                            t.HasCheckConstraint("CK_SlaEscalation_CustomAddress", "([RecipientType] <> N'Custom' OR [RecipientAddress] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SlaEscalation_Level", "([Level] BETWEEN 1 AND 4)");

                            t.HasCheckConstraint("CK_SlaEscalation_RecipientType", "([RecipientType] IN (N'AssignedTechnician', N'TeamLead', N'BranchAdmin', N'Manager', N'Custom'))");

                            t.HasCheckConstraint("CK_SlaEscalation_Threshold", "([ThresholdPercent] BETWEEN 1 AND 1000)");

                            t.HasCheckConstraint("CK_SlaEscalation_Type", "([EscalationType] IN (N'Response', N'Resolution'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.SlaEscalationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("EmailOutboxId")
                        .HasColumnType("bigint");

                    b.Property<string>("EscalationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FiredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SentTo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int>("SlaEscalationId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_SlaEscalationLog");

                    b.HasIndex("ServiceRequestId", "FiredOnUtc")
                        .HasDatabaseName("IX_SlaEscalationLog_Request");

                    b.HasIndex("ServiceRequestId", "SlaEscalationId")
                        .IsUnique()
                        .HasDatabaseName("UX_SlaEscalationLog_OncePerLevel")
                        .HasFilter("[Outcome] <> N'Failed'");

                    b.ToTable("SlaEscalationLog", "ServiceLevel", t =>
                        {
                            t.HasCheckConstraint("CK_SlaEscalationLog_Outcome", "([Outcome] IN (N'Queued', N'Sent', N'Failed', N'Skipped'))");
                        });
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.SlaPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NearDueWarningMinutes")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ResolutionTargetMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("RespectHolidays")
                        .HasColumnType("bit");

                    b.Property<bool>("RespectOperationalHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<bool>("RespectWeekends")
                        .HasColumnType("bit");

                    b.Property<int>("ResponseTargetMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime");

                    b.HasKey("Id")
                        .HasName("PK_SlaPolicy");

                    b.HasIndex("PolicyName")
                        .IsUnique()
                        .HasDatabaseName("UX_SlaPolicy_Name");

                    b.HasIndex("Priority")
                        .IsUnique()
                        .HasDatabaseName("UX_SlaPolicy_ActivePriority")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("SlaPolicy", "ServiceLevel", t =>
                        {
                            t.HasCheckConstraint("CK_SlaPolicy_NearDue", "([NearDueWarningMinutes] >= 0)");

                            t.HasCheckConstraint("CK_SlaPolicy_Priority", "([Priority] IN (N'Low', N'Medium', N'High', N'Critical'))");

                            t.HasCheckConstraint("CK_SlaPolicy_ResponseWithinResolution", "([ResponseTargetMinutes] <= [ResolutionTargetMinutes])");

                            t.HasCheckConstraint("CK_SlaPolicy_Targets", "([ResponseTargetMinutes] > 0 AND [ResolutionTargetMinutes] > 0)");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("SlaPolicyHistory", "ServiceLevel");
                                ttb
                                    .HasPeriodStart("SysStartTime")
                                    .HasColumnName("SysStartTime");
                                ttb
                                    .HasPeriodEnd("SysEndTime")
                                    .HasColumnName("SysEndTime");
                            }));
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.HolidayLocation", b =>
                {
                    b.HasOne("AMS.Modules.ServiceLevel.Domain.HolidayCalendar", null)
                        .WithMany()
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HolidayLocation_HolidayCalendar_HolidayCalendarId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.LocationOperationalDay", b =>
                {
                    b.HasOne("AMS.Modules.ServiceLevel.Domain.LocationOperationalHour", null)
                        .WithMany()
                        .HasForeignKey("LocationOperationalHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LocationOperationalDay_LocationOperationalHour_LocationOperationalHourId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.LocationSaturdayRule", b =>
                {
                    b.HasOne("AMS.Modules.ServiceLevel.Domain.LocationOperationalHour", null)
                        .WithMany()
                        .HasForeignKey("LocationOperationalHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LocationSaturdayRule_LocationOperationalHour_LocationOperationalHourId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.SlaEscalation", b =>
                {
                    b.HasOne("AMS.Modules.ServiceLevel.Domain.SlaPolicy", null)
                        .WithMany()
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SlaEscalation_SlaPolicy_SlaPolicyId");
                });

            modelBuilder.Entity("AMS.Modules.ServiceLevel.Domain.SlaEscalationLog", b =>
                {
                    b.HasOne("AMS.Modules.ServiceLevel.Domain.SlaEscalation", null)
                        .WithMany()
                        .HasForeignKey("SlaEscalationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SlaEscalationLog_SlaEscalation_SlaEscalationId");
                });
#pragma warning restore 612, 618
        }
    }
}
